float64 spherical_resemblance                           # How well the object resembles a spherical
float64 cylindrical_resemblance
float64 cuboid_resemblance
float64 elongatedness                                   # The ratio of the minor axes to the major axis
float64 grasp_position                                  # The ratio of the position of the grasp on the main axes to the main axes
int32 opening                                           # The binary value for the existence of opening
float64 opening_grasp_angle                             # The angel between the opening normal and the grasp
float64 opening_grasp_distance                          # The signed distance from the grasp to the opening plane
float64 FPFH
float64 first_gradient
float64 second_gradient
float64 third_gradient
float64 intensity
float64 grasp_color                                     #
float64 color_uniformity                                #

int32 label